[package]
name = "app"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "staticlib"]
name = "mobile"
 
[dependencies]
base64 = "0.22.1"
serde_json = "1.0.137"
thiserror = "2.0.11"
uniffi = { version = "0.29.2", features = [ "cli" ] }
